name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn fmt:check

      - name: Build
        run: yarn package

      - name: Publish
        if: |
          success() &&
          runner.os == 'Linux' &&
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/')
        run: yarn publish --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}

      - name: Upload extension installer to artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocaml-platform-${{ matrix.os }}-${{ github.sha }}
          path: ocaml-platform-*.vsix
